### ISSUE TITLE
require 'some-module/blah'

### ISSUE THREAD

**Issue by Gaelan** [vazco/meteor-universe-modules-npm#2]
Is there any way to import files from packages other than the main file?

**Comment by cristo-rabani** [comment]
Yes,  but it works from last version

Example:

lets assume we have added package  `"react-widgets": "2.8.2",` in file `myPacks.npm.json`

And path inside is `./lib/globalize-localizers.js`

```
import {globalizeDateLocalizer} from '/myPacks/react-widgets/lib/globalize-localizers';
```
