### ISSUE TITLE
npm modules not getting picked up by transformer/babel

### ISSUE THREAD

**Issue by rozzzly** [vazco/meteor-universe-modules-npm#3]
@cristo-rabani  First off I'd like to say great work! I've been using the universe:modules family for a while now and have been very pleased. Today I found this (`meteor-universe-modules-npm`) and was very sad to see that it's not currently working. I know you've been pushing a lot of significant changes to the other repos today, but I'd really appreciate it if you could take a look back at this.

> `[Universe Modules]: Trying to load module "/rozzzly/immutable/myPacks" that doesn't exist!`
> 
> `Error loading /_modules_/packages/rozzzly/immutable/myPacks as "{rozzzly:immutable}/myPacks" from /_modules_/app/both/router`

Crawling though `.meteor/local` I can see that the npm package gets downloaded, but it never gets touched by babel. I think this may be because with the update to `meteor@1.2.1`, we loose the `api.addFiles(...)` function for some file types,  as a result I had to use `api.addAssets(...)` to include `myPacks.npm.json`. It obviously still gets picked up by the build plugin because the node module gets downloaded, but I have a hunch that it doesn't get "compiled" because it's no longer being treated as a source file? This is all speculation. I'm going to try to fork this, see what I can do (it does have an outdated dep on `universe:modules`, but I don't think that's the issue). If there's any more info I can give you that would help diagnose, I'd be glad to supply it.

**Comment by cristo-rabani** [comment]
Hello Rozzzly ,
In my free time I can check for you this issue.
But in the meantime please try:
turn off meteor
`myPacks.npm.json` must be added by api.addFiles always
clean up cache in meteor project ( in `.meteor/local` dirs: `build/, bundler-cache/, plugin-cache/` )

go to your tmp directory on linux it should be `/tmp/`
on windows `%userprofile%\AppData\Local\Temp`
on mac `open $TMPDIR`

run meteor again

p.s. on windows are problems with paths (it will be fixed soon)

**Comment by rozzzly** [comment]
I ended up figuring it outmyself. I will post a PR tomorrow afternoon with some bugfixes/improvements.

great work tho man

**Comment by cristo-rabani** [comment]
Hello, 
Please check new version `0.9.7` it  should be fixed
