### ISSUE TITLE
Using typescript: Cannot find module

### ISSUE THREAD

**Issue by twastvedt** [vazco/meteor-universe-modules-npm#5]
Will this work with Typescript? I'm using [angular2-meteor](https://github.com/Urigo/angular2-meteor), which uses [barbatus:angular2](https://github.com/barbatus/angular2), which uses [barbatus:ts-compilers](https://github.com/barbatus/ts-compilers) to compile Typescript. When I run `meteor` I get the following error:

```
ERROR: packages.json parsing error [ ENOENT, no such file or directory 'C:\Users\twastvedt\Documents\Zahner\Alfred-Zahner\packages.json' ]
=> Meteor server restartedERROR: packages.json parsing error [ ENOENT, no such file or directory 'C:\Users\twastvedt\Documents\Zahner\Alfred-Zahner\packages.json' ]

=> Errors prevented startup:

   While processing files with barbatus:angular2 (for target web.browser):
   client/modals/projectEventEdit/ProjectEventEdit.ts:21:26: Cannot find module 'universePackages/rxjs'.

=> Your application has errors. Waiting for file change.
```

I have a file `universePackages.npm.json` like so:

```
{
    "packages": {
        "rxjs": "5.0.0-beta.1"
    }
}
```

and an import line in one of my Typescript files:
`import {Observable} from 'universePackages/rxjs';`

Universe NPM installs rxjs, and if I remove the offending import line, the app builds and the node_modules folder shows up in Sources in Chrome, but when Typescript is compiling it doesn't know about, or can't find the rxjs package. Am I doing something wrong, or is this not designed to work in this way?

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
