### ISSUE TITLE
Downloading older version of the package rather than the one listed in *.npm.json file

### ISSUE THREAD

**Issue by veeramarni** [vazco/meteor-universe-modules-npm#6]
I'm using this module in a package where i put all the dependencies in `package.npm.json` file as show below. But i have noticed it is loading older version for one of the package. In my case, the generated app_package.js file has the same code as of `react-tappable:0.5.1` instead of the version `0.7.1`. This causing loading issue as it depend on older react (0.13 version). I tried to troubleshoot the issue for hours but I couldn't track down the npm package which this univers module is trying to pick. Can you shed some light where should i look for and why it is picking wrong version?

```
{
  "packages": {
    "react-tappable": "0.7.1",
    "touchstonejs": "0.7.3",
    "moment": "2.10.3"
  },
  "system": {
    // In bundle "react" will be replaced by universe:modules dependency.
    "dependencies": [
      "react",
      "react-dom",
      "react-addons-css-transition-group"
    ]
  }
}
```

**Comment by veeramarni** [comment]
After struggling for few hours, i had found the npm location from where it is loading. Seems like even the package version is changed, it is not updating the right version at the npm repository location.

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
